# Generated by Django 4.1.1 on 2022-10-12 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
