# Generated by Django 4.1.3 on 2022-11-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default="2022-11-14 22:02:26.974397 +00:00"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contacts",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
