# Generated by Django 4.1.1 on 2022-10-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts_db", "0002_contacts_created_at_contacts_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
